In [2]:
import numpy as np
print(np.arange(2,10))

[2 3 4 5 6 7 8 9]


In [13]:
arr = np.array([1,2,3.3])
type(arr)
print(arr)

[1.  2.  3.3]


In [14]:
# >>> a = np.array(1,2,3,4)    # WRONG
# >>> a = np.array([1,2,3,4])  # RIGHT

In [15]:
# array transforms sequences of sequences into two-dimensional arrays, 
# sequences of sequences of sequences into three-dimensional arrays, and so on.
b = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
b = np.array([1,2,3,4,5,6,7,8,9])
print(b)

[1 2 3 4 5 6 7 8 9]


In [19]:
c = np.array([[1,2,3],[4,5,6]],dtype = "float")
print(c)
c = np.array([[1,2,3],[4,5,6]],dtype = "complex")
print(c)

[[1. 2. 3.]
 [4. 5. 6.]]
[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]


In [26]:
d = np.ones((3,3))
print(d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [28]:
#returns a one array same as the given array
e = np.ones_like(b)
e

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [31]:
f = np.arange(10,99,4)
f

array([10, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50, 54, 58, 62, 66, 70, 74,
       78, 82, 86, 90, 94, 98])

In [34]:
g = np.linspace(4,50,6)
g
h = np.sin(g)
h

array([-0.7568025 ,  0.59207351, -0.39755568,  0.18303573,  0.04069326,
       -0.26237485])

In [36]:
#numpy.random.rand
#Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).
i = np.random.randn(2,3)
i

array([[ 0.42637278,  0.84124177,  0.37954623],
       [-0.7322222 ,  1.49842884, -0.2991258 ]])

In [37]:
print(np.fromfunction(lambda i, j: i + j, (3, 3), dtype=int))

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [3]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
b

c = a-b
c

b**2

10*np.sin(a)

a<35

A = np.array( [[1,1],
            [0,1]] )
B = np.array( [[2,0],
            [3,4]] )
A * B                       # elementwise product


A @ B                       # matrix product


A.dot(B)                    # another matrix product



array([[5, 4],
       [3, 4]])

In [4]:
b**2

array([0, 1, 4, 9])

In [5]:
a<35

array([ True,  True, False, False])

In [6]:
A * B 

array([[2, 0],
       [0, 4]])

In [10]:
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))
a *= 3
a


b += a
b


a += b                  # b is not automatically converted to integer type


TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [16]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0,3.14,3)
b.dtype.name

c = a+b
c

c.dtype.name

d = np.exp(c*1j)
d


d.dtype.name


'complex128'

In [20]:
a = np.random.random((2,3))
a

a.sum()
a.min()
a.max()


0.9388468711834068

In [27]:
b = np.arange(12).reshape(3,4)
print(b)
print(b.sum(axis=0))                          # sum of each column
b.min(axis=0)                            # min of each row
b.cumsum(axis=1)                         # cumulative sum along each row

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]


array([0, 1, 2, 3])

In [29]:
# numpy.apply_along_axis
# numpy.apply_along_axis(func1d, axis, arr, *args, **kwargs)[source]
# Apply a function to 1-D slices along the given axis.

def my_func(a):
    """Average first and last element of a 1-D array"""
    return (a[0] + a[-1]) * 0.5
b = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(np.apply_along_axis(my_func, 0, b))

print(np.apply_along_axis(my_func, 1, b))

[4. 5. 6.]
[2. 5. 8.]


In [30]:
b = np.array([[8,1,7], [4,3,9], [5,2,6]])
np.apply_along_axis(sorted, 1, b)

array([[1, 7, 8],
       [3, 4, 9],
       [2, 5, 6]])

In [31]:
b = np.array([[1,2,3], [4,5,6], [7,8,9]])
np.apply_along_axis(np.diag, -1, b)

array([[[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]],

       [[4, 0, 0],
        [0, 5, 0],
        [0, 0, 6]],

       [[7, 0, 0],
        [0, 8, 0],
        [0, 0, 9]]])

In [32]:
# numpy.apply_over_axes
# numpy.apply_over_axes(func, a, axes)[source]
# Apply a function repeatedly over multiple axes.

a = np.arange(24).reshape(2,3,4)
a
np.apply_over_axes(np.sum, a, [0,2])


array([[[ 60],
        [ 92],
        [124]]])

In [33]:
x = np.array([3, 1, 2])
np.argsort(x)

array([1, 2, 0])

In [34]:
data = list(range(1,5))
data
[1, 2, 3, 4]
np.average(data)
2.5
np.average(range(1,11), weights=range(10,0,-1))
4.0

4.0

In [37]:
np.bincount(np.arange(5))

np.bincount(np.array([0, 1, 1, 3, 2, 1, 7]))

array([1, 3, 1, 1, 0, 0, 0, 1])

In [38]:
a = np.arange(10)**3
a

a[2]

a[2:5]

a[:6:2] = -1000    # equivalent to a[0:6:2] = -1000; from start to position 6, exclusive, set every 2nd element to -1000
a

a[ : :-1]                                 # reversed a

for i in a:
    print(i**(1/3.))


nan
1.0
nan
3.0
nan
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


/Users/amit.panda03/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:14: RuntimeWarning: invalid value encountered in power
  


In [39]:
def f(x,y):
    return 10*x+y

b = np.fromfunction(f,(5,4),dtype=int)
b





b[2,3]

b[0:5, 1]                       # each row in the second column of b

b[ : ,1]                        # equivalent to the previous example

b[1:3, : ]                      # each column in the second and third row of b

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [40]:
b[-1]                                  # the last row. Equivalent to b[-1,:]

array([40, 41, 42, 43])

In [41]:
c = np.array( [[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
                [ 10, 12, 13]],
               [[100,101,102],
                [110,112,113]]])
c.shape

c[1,...]                                   # same as c[1,:,:] or c[1]


c[...,2]                                   # same as c[:,:,2]


array([[  2,  13],
       [102, 113]])

In [42]:
for row in b:
    print(row)


[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [43]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [44]:
#Shape Manipulation

a = np.floor(10*np.random.random((3,4)))
print(a)
a.shape

[[5. 0. 3. 5.]
 [5. 8. 8. 8.]
 [3. 8. 6. 6.]]


(3, 4)

In [46]:
print(a.ravel())  # returns the array, flattened
print(a.reshape(6,2))  # returns the array with a modified shape
print(a.T)  # returns the array, transposed
print(a.T.shape)
print(a.shape)

[5. 0. 3. 5. 5. 8. 8. 8. 3. 8. 6. 6.]
[[5. 0.]
 [3. 5.]
 [5. 8.]
 [8. 8.]
 [3. 8.]
 [6. 6.]]
[[5. 5. 3.]
 [0. 8. 8.]
 [3. 8. 6.]
 [5. 8. 6.]]
(4, 3)
(3, 4)


In [47]:
print(a)
print(a.resize((2,6)))
a

[[5. 0. 3. 5.]
 [5. 8. 8. 8.]
 [3. 8. 6. 6.]]
None


array([[5., 0., 3., 5., 5., 8.],
       [8., 8., 3., 8., 6., 6.]])

In [48]:
a.reshape(3,-1)

array([[5., 0., 3., 5.],
       [5., 8., 8., 8.],
       [3., 8., 6., 6.]])

In [49]:
a = np.floor(10*np.random.random((2,2)))
print(a)

b = np.floor(10*np.random.random((2,2)))
print(b)
print(np.vstack((a,b)))
print(np.hstack((a,b)))


[[0. 4.]
 [7. 6.]]
[[7. 5.]
 [5. 4.]]
[[0. 4.]
 [7. 6.]
 [7. 5.]
 [5. 4.]]
[[0. 4. 7. 5.]
 [7. 6. 5. 4.]]


In [51]:
from numpy import newaxis
print(np.column_stack((a,b)))     # with 2D arrays
a = np.array([4.,2.])
b = np.array([3.,8.])
print(np.column_stack((a,b)))    # returns a 2D array
print(np.hstack((a,b)))           # the result is different
print(a[:,newaxis]  )             # this allows to have a 2D columns vector
print(np.column_stack((a[:,newaxis],b[:,newaxis])))
print(np.hstack((a[:,newaxis],b[:,newaxis])))   # the result is the same

[[0. 4. 7. 5.]
 [7. 6. 5. 4.]]
[[4. 3.]
 [2. 8.]]
[4. 2. 3. 8.]
[[4.]
 [2.]]
[[4. 3.]
 [2. 8.]]
[[4. 3.]
 [2. 8.]]


In [52]:
a = np.arange(12)**2                       # the first 12 square numbers
i = np.array( [ 1,1,3,8,5 ] )              # an array of indices
a[i]                                       # the elements of a at the positions i


j = np.array( [ [ 3, 4], [ 9, 7 ] ] )      # a bidimensional array of indices
a[j]                                       # the same shape as j

array([[ 9, 16],
       [81, 49]])

In [55]:
a = np.arange(12).reshape(3,4)
print(a)



i = np.array( [ [0,1],                        # indices for the first dim of a
                [1,2] ] )
j = np.array( [ [2,1],                        # indices for the second dim
                [3,3] ] )

a[i,j]                                     # i and j must have equal shape



#a[i,2]



#a[:,j]                                     # i.e., a[ : , j]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 2,  5],
       [ 7, 11]])