In [8]:
def grad(name,course = "BTech"):
    print("Name: ",name)
    print("Course: ",course)

grad(name = "amit",course = "btech")

Name:  amit
Course:  btech


In [11]:
x = lambda x: 2**4
print(x(3))

16


In [12]:
print("THis is Python Class" , "And its a sunday" + "mornig")

THis is Python Class And its a sundaymornig


In [39]:
strs = "hHelloWorld @1sNNjNJjnkjn"
print(strs.capitalize())

Hhelloworld @1snnjnjjnkjn


In [20]:
str = "hello"
print(str.center(10,'*'))

**hello***


In [22]:
str = "he"
message = "helloworldhellohellohe"
print(message.count(str,0,4))

1


In [27]:
str = "The world is beautiful"
print(str.endswith("ti",0,-3))

True


In [31]:
message = "he is my best friend"
print(message.find("my",0,8))

6


In [41]:
message = "aB"
message.isalnum()

True

In [43]:
message.islower()

False

In [56]:
#ljust and rjust
str = "hello"
print(str.ljust(6,"*"))
print(str.rjust(-10,"*"))
print(str.center(-10,"*"))

hello*
hello
hello


In [58]:
#zfill
#automatically left padding of zeros to the  string
str = "1234"
print(str.zfill(0))

1234


In [70]:
str = " he353E@#Llo efez "
str.upper()
str.lower()
str.strip()
max(str)

'z'

In [73]:
#replace()
str = "heLLo hello hello"
print(str.replace("he","fo"))

foLLo follo follo


In [74]:
#swapcase()
print(str.swapcase())


HEllO HELLO HELLO


In [75]:
#enumerate()
str = "Hello World"
print(list(enumerate(str)))

[(0, 'H'), (1, 'e'), (2, 'l'), (3, 'l'), (4, 'o'), (5, ' '), (6, 'W'), (7, 'o'), (8, 'r'), (9, 'l'), (10, 'd')]


In [76]:
list1 = ['1','a',"abc",'2','B',"Def",'%','$','#']
list1.sort()
print(list1)

['#', '$', '%', '1', '2', 'B', 'Def', 'a', 'abc']


In [77]:
list1

['#', '$', '%', '1', '2', 'B', 'Def', 'a', 'abc']

In [78]:
list1.pop(3)

'1'

In [79]:
list1

['#', '$', '%', '2', 'B', 'Def', 'a', 'abc']

In [80]:
list1.remove("2")

In [81]:
list1

['#', '$', '%', 'B', 'Def', 'a', 'abc']

In [82]:
list1.remove(0)

ValueError: list.remove(x): x not in list

In [83]:
import re
text = "The rain in Spain"

In [84]:
#findall
#search
#split
#sub

In [85]:
# []	A set of characters	"[a-m]"	
# \	Signals a special sequence (can also be used to escape special characters)	"\d"	
# .	Any character (except newline character)	"he..o"	
# ^	Starts with	"^hello"	
# $	Ends with	"world$"	
# *	Zero or more occurrences	"aix*"	
# +	One or more occurrences	"aix+"	
# {}	Exactly the specified number of occurrences	"al{2}"	
# |	Either or	"falls|stays"	
# ()	Capture and group

In [89]:
re.findall("[M-a]",text)

['T', 'a', 'S', 'a']

In [91]:
re.search("[a-m]",text).lastgroup

In [95]:
a = "hello heo"
re.findall("^h.l",a)

['hel']

In [96]:
import re
str = "The rain in Spain falls mainly in the plain!"
#Check if the string contains "a" followed by exactly two "l" characters:
x = re.findall("al{2}", str)
print(x)
if (x):
  print("Yes, there is at least one match!")
else:
  print("No match")

['all']
Yes, there is at least one match!


In [97]:
import re
str = "The rain in Spain falls mainly in the plain!"
#Check if the string contains "ai" followed by 1 or more "x" characters:
x = re.findall("aix+", str)
print(x)
if (x):
  print("Yes, there is at least one match!")
else:
  print("No match")

[]
No match


In [98]:
import re

str = "The rain in Spain falls mainly in the plain!"

#Check if the string contains "ai" followed by 0 or more "x" characters:

x = re.findall("aix*", str)

print(x)

if (x):
  print("Yes, there is at least one match!")
else:
  print("No match")

['ai', 'ai', 'ai', 'ai']
Yes, there is at least one match!


In [99]:
# [arn]	Returns a match where one of the specified characters (a, r, or n) are present	
# [a-n]	Returns a match for any lower case character, alphabetically between a and n	
# [^arn]	Returns a match for any character EXCEPT a, r, and n	
# [0123]	Returns a match where any of the specified digits (0, 1, 2, or 3) are present	
# [0-9]	Returns a match for any digit between 0 and 9	
# [0-5][0-9]	Returns a match for any two-digit numbers from 00 and 59	
# [a-zA-Z]	Returns a match for any character alphabetically between a and z, lower case OR upper case	
# [+]	In sets, +, *, ., |, (), $,{} has no special meaning, so [+] means: return a match for any + character in the string	


In [104]:
import re

str = "The rain in Spain"
x = re.search("\s", str)

print("The first white-space character is located in position:", x.end())

The first white-space character is located in position: 4


In [106]:
import re

str = "The rain in Spain"
x = re.split("a", str)
print(x)

['The r', 'in in Sp', 'in']


In [107]:
import re

str = "The rain in Spain"
x = re.sub("\s", "9", str)
print(x)

The9rain9in9Spain


In [108]:
import re

str = "The rain in Spain"
x = re.search("ai", str)
print(x)

<re.Match object; span=(5, 7), match='ai'>


In [111]:
import re
#span()
#Print the position (start- and end-position) of the first match occurrence.

str = "The rain in Spain"
x = re.search(r"\bS\w+", str)
print(x.span())
print(x.group())

(12, 17)
Spain


In [122]:
str

'The rain in Spain'

In [129]:
str[1:10:4]

'hai'

In [1]:
print(38 ** 41 / (2.178 ** 38))

8.412560399488753e+51


In [2]:
print(841//3.34)

251.0


In [3]:
import numpy as np
print(np.nan == np.nan)

False


In [5]:
import pandas as pd
df = pd.DataFrame([[2,5],
                   [56,20]],
                   index = list('pq'),
                    columns = list('ab'))
df

a   b
p   2   5
q  56  20

In [6]:
def loc(a,b):
    try:
        out = df.loc[a,b]
    except:
        return 0
    return out

def iloc(a,b):
    try:
        out = df.iloc[a,b]
    except:
        return 0
    return out    
        
print( iloc(0,'b') )
print( loc(0,'b') )
print( loc('q','a') )
print( iloc('q','b') )

0
0
56
0


In [9]:
df.iloc[0:1,]

a  b
p  2  5

In [10]:
df.iloc[1]

a    56
b    20
Name: q, dtype: int64

In [13]:
df.iloc[0:1,1]

p    5
Name: b, dtype: int64

In [14]:
import numpy as np

arr1 = np.arange(4).reshape(2,2)
arr2 = arr1.copy()
arr2[1,1] = 50 
print(arr1)

[[0 1]
 [2 3]]


In [15]:
import pandas as pd

df = pd.DataFrame([[15, 12],
                   [33, 54],
                   [10, 32]], 
                   index = ['one','two','three'],
                   columns = ['col1', 'col2'])

print(df.filter(regex = 'e$', axis = 0).shape)
print(df.filter(regex = '^c', axis = 1).shape)

(2, 2)
(3, 2)


In [16]:
import pandas as pd

df1 = pd.DataFrame({'A': [1,4,7],
                    'B': [2,5,8],
                    'C': [3,6,9]},
                    index = list('PQR'))
df1

A  B  C
P  1  2  3
Q  4  5  6
R  7  8  9

In [17]:
import pandas as pd

df1 = pd.DataFrame({'A': [1,4,7],
                    'B': [2,5,8],
                    'C': [3,6,9]},
                    index = list('PQR'))
df3 = pd.DataFrame({'A': [1,-4,-7],
                    'B': [-2,5,-8],
                    'C': [-3,-6,9]},
                    index = list('STU'))
print(df1.sub(df3).count())

A    0
B    0
C    0
dtype: int64


In [18]:
print(np.nan+3)

nan


In [62]:
import pandas as pd

df = pd.DataFrame([[np.nan, 2, np.nan, 0], 
                   [3, 4, np.nan, 1],
                   [np.nan, np.nan, np.nan, 5]],
                   columns=list('ABCD'))
df.cumsum(axis=1)
print(df)
print(df.cumsum(axis=1))
print(df.dropna(axis = 1, how = 'all'))
print(df.dropna(axis = 1, how='any'))

     A    B   C  D
0  NaN  2.0 NaN  0
1  3.0  4.0 NaN  1
2  NaN  NaN NaN  5
     A    B   C    D
0  NaN  2.0 NaN  2.0
1  3.0  7.0 NaN  8.0
2  NaN  NaN NaN  5.0
     A    B  D
0  NaN  2.0  0
1  3.0  4.0  1
2  NaN  NaN  5
   D
0  0
1  1
2  5


In [20]:
import numpy as np

mat1 = np.array([[ 0,  1,  2,  3],
                 [ 4,  5,  6,  7],
                 [ 8,  9, 10, 11]])

indA = np.array([[2,2],[1,1]])
indB = np.array([[2,1],[1,0]])

mat1[indA, indB] = np.array([[100, 90],[50, 40]])
print(mat1)


[[  0   1   2   3]
 [ 40  50   6   7]
 [  8  90 100  11]]


In [30]:
arr = np.array([1,2,5,4,6,8,3,2,1,4,5,7,8,562,1,2,4,5])
#print(arr.reshape(3,-1).shape)
arr.reshape(3,6)
arr

array([  1,   2,   5,   4,   6,   8,   3,   2,   1,   4,   5,   7,   8,
       562,   1,   2,   4,   5])

In [32]:
arr = np.array([1,2,5,4,6,8,3,2,1,4,5,7,8,562,1,2,4,5])
#print(arr.reshape(3,-1).shape)
arr.resize(6,3)
arr

array([[  1,   2,   5],
       [  4,   6,   8],
       [  3,   2,   1],
       [  4,   5,   7],
       [  8, 562,   1],
       [  2,   4,   5]])

In [33]:
df  = pd.DataFrame({'P1':[10,20,30],'P2':[["A","B","C"],["A","D","E"],["C","D","F"]]})
df

P1         P2
0  10  [A, B, C]
1  20  [A, D, E]
2  30  [C, D, F]

In [35]:
import pandas as pd

df  = pd.DataFrame({'P1':[10,20,30],'P2':[["A","B","C"],["A","D","E"],["C","D","F"]]})
df['P3'] = df["P2"].apply(lambda x: " ".join(["_".join(i.split(" ")) for i in x]))
print (df)

   P1         P2     P3
0  10  [A, B, C]  A B C
1  20  [A, D, E]  A D E
2  30  [C, D, F]  C D F


In [40]:
df = pd.DataFrame({"A":[1,2,3],"B":[4,5,6],"C":["yes","no","yes"]})
df

A  B    C
0  1  4  yes
1  2  5   no
2  3  6  yes

In [39]:
df[df.loc[:,'C'] == 'yes'] = 1 
df[df.loc[:,'C'] == 'no'] = 0
df

A  B  C
0  1  1  1
1  0  0  0
2  1  1  1

In [43]:
df[df.loc[::,'C'] == 'yes'] = 1 
df[df.loc[::,'C'] == 'no'] = 0
df

A  B  C
0  1  1  1
1  0  0  0
2  1  1  1

In [45]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [52]:
arr.ravel()
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [53]:
df.head(1)

A  B  C
0  1  1  1

In [54]:
df

A  B  C
0  1  1  1
1  0  0  0
2  1  1  1

In [55]:
df["A"]

0    1
1    0
2    1
Name: A, dtype: int64

In [58]:
df.loc[:,"A"]

0    1
1    0
2    1
Name: A, dtype: int64